link frontend to api
SYSC4806-Group13/SYSC4806-Project pull request #35
Opened 2023-03-05 16:29 UTC by Justgo13

2023-03-05 16:46 UTC, MillanWang requested changes
Very good functionality-wise

Could you add some tests that mock an API response from the /listings GET endpoint, and then verify that the info from the response gets shown in the DOM?

2023-03-05 19:45 UTC, Justgo13 commented
> Very good functionality-wise
> 
> Could you add some tests that mock an API response from the /listings GET endpoint, and then verify that the info from the response gets shown in the DOM?

added changes

2023-03-07 01:49 UTC, NosBos approved these changes
looks good

2023-03-07 01:50 UTC, MillanWang approved these changes

2023-03-07 01:50 UTC, kfoxIsProgrammer reviewed
This looks good

2023-03-07 01:50 UTC, kfoxIsProgrammer commented on frontend/src/pages/SellerListings.tsx
> +    React.useEffect(() => {
This is just a stylistic pet peeve choice. Import React, {useEffect} from "react"

Then just use useEffect as a method itself.

2023-03-07 01:58 UTC, merged